name: Continuous Integration

on:
  push:
    branches: [ main ]
    paths:
    - 'TtxFromTS/**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Build
      run: dotnet build
  dotnet-format:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format
      - name: name: Checkout repository
        uses: actions/checkout@v2
      - name: Add dotnet-format problem matcher
        uses: xt0rted/dotnet-format-problem-matcher@v1
      - name: Run dotnet format
        uses: xt0rted/dotnet-format@v1
        with:
          only-changed-files: "true"
  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: csharp
        queries: +security-extended
    - name: Autobuild
      uses: github/codeql-action/autobuild@v1
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
