name: TtxFromTS Continuous Integration

on:
  push:
    branches: [ next ]
    paths:
    - 'TtxFromTS/**'
  pull_request:
    branches: [ next ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: dotnet restore
    - name: Windows x64 build
      run: dotnet publish --runtime win-x64 --configuration Release
    - name: Upload Windows x64 artifact
      uses: actions/upload-artifact@v2
      with:
        name: win-x64
        path: TtxFromTS/bin/Release/netcoreapp3.1/win-x64/publish
    - name: Windows x86 build
      run: dotnet publish --runtime win-x86 --configuration Release
    - name: Upload Windows x86 artifact
      uses: actions/upload-artifact@v2
      with:
        name: win-x86
        path: TtxFromTS/bin/Release/netcoreapp3.1/win-x86/publish
    - name: macOS build
      run: dotnet publish --runtime osx-x64 --configuration Release
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v2
      with:
        name: macos-x64
        path: TtxFromTS/bin/Release/netcoreapp3.1/osx-x64/publish
    - name: Ubuntu build
      run: dotnet publish --runtime ubuntu-x64 --configuration Release
    - name: Upload Ubuntu artifact
      uses: actions/upload-artifact@v2
      with:
        name: ubuntu-x64
        path: TtxFromTS/bin/Release/netcoreapp3.1/ubuntu-x64/publish
    - name: Debian build
      run: dotnet publish --runtime debian-x64 --configuration Release
    - name: Upload Debian artifact
      uses: actions/upload-artifact@v2
      with:
        name: debian-x64
        path: TtxFromTS/bin/Release/netcoreapp3.1/debian-x64/publish
