name: Nightly Artifact Cleanup

on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  clean-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Clean Artifacts
        uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 7days
