name: Nightly Build

on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  commit-check:
    name: Check if build should run
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ steps.check.outputs.should-run }}
    steps:
      - uses: actions/checkout@v2
      - name: Get latest commit hash
        run: echo ${{ github.sha }}
      - id: check
        continue-on-error: true
        name: Check for commits in the last 24 hours
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list --after="24 hours" --max-count=1 ${{ github.sha }}) && echo "::set-output name=should-run::false"
  windows-x64-build:
    name: Windows x64 build
    runs-on: windows-latest
    needs: commit-check
    if: ${{ needs.commit-check.outputs.should-run != 'false' }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Build
      run: dotnet publish --runtime win-x64 --configuration Release
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: win-x64
        path: TtxFromTS/bin/Release/net5.0/win-x64/publish
        retention-days: 7
  windows-x86-build:
    name: Windows x86 build
    runs-on: windows-latest
    needs: commit-check
    if: ${{ needs.commit-check.outputs.should-run != 'false' }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Build
      run: dotnet publish --runtime win-x86 --configuration Release
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: win-x86
        path: TtxFromTS/bin/Release/net5.0/win-x86/publish
        retention-days: 7
  windows-arm-build:
    name: Windows ARM build
    runs-on: windows-latest
    needs: commit-check
    if: ${{ needs.commit-check.outputs.should-run != 'false' }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Build
      run: dotnet publish --runtime win-arm64 --configuration Release
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: win-arm64
        path: TtxFromTS/bin/Release/net5.0/win-arm64/publish
        retention-days: 7
  macos-build:
    name: macOS build
    runs-on: macos-latest
    needs: commit-check
    if: ${{ needs.commit-check.outputs.should-run != 'false' }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Build
      run: dotnet publish --runtime osx-x64 --configuration Release
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: macos-x64
        path: TtxFromTS/bin/Release/net5.0/osx-x64/publish
        retention-days: 7
  linux-x64-build:
    name: Linux x64 build
    runs-on: ubuntu-latest
    needs: commit-check
    if: ${{ needs.commit-check.outputs.should-run != 'false' }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Build
      run: dotnet publish --runtime linux-x64 --configuration Release
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux-x64
        path: TtxFromTS/bin/Release/net5.0/linux-x64/publish
        retention-days: 7
  linux-arm-build:
    name: Linux ARM build
    runs-on: ubuntu-latest
    needs: commit-check
    if: ${{ needs.commit-check.outputs.should-run != 'false' }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Build
      run: dotnet publish --runtime linux-arm --configuration Release
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux-arm
        path: TtxFromTS/bin/Release/net5.0/linux-arm/publish
        retention-days: 7
